// Generated by scripts/prepare_assets.py --set revised
import type { ImageSourcePropType } from 'react-native';
export const revisedAssets: Record<string, { source: ImageSourcePropType; width: number; height: number; alt: string }> = {
  'p003_school_children': { source: require('../../assets/book2/p003_school_children.png'), width: 680, height: 578, alt: "8 детей идут к современной школе: две девочки, два мальчика и две смешанные пары" },
  'p003_balls_bigger_smaller': { source: require('../../assets/book2/p003_balls_bigger_smaller.png'), width: 887, height: 439, alt: "большой бирюзовый мяч слева и маленький красный мяч справа" },
  'p003_pencils_longer_shorter': { source: require('../../assets/book2/p003_pencils_longer_shorter.png'), width: 1010, height: 382, alt: "длинный зелёный карандаш сверху и короткий красный снизу" },
};
