// Generated by scripts/prepare_assets.py --set revised
import type { ImageSourcePropType } from 'react-native';
export const revisedAssets: Record<string, { source: ImageSourcePropType; width: number; height: number; alt: string }> = {
  'p001_cover_mushroom_1': { source: require('../../assets/book2/p001_cover_mushroom_1.png'), width: 240, height: 240, alt: "один белый гриб и цифра 1" },
  'p001_cover_acorns_2': { source: require('../../assets/book2/p001_cover_acorns_2.png'), width: 240, height: 240, alt: "два жёлудя и цифра 2" },
  'p001_cover_daisies_3': { source: require('../../assets/book2/p001_cover_daisies_3.png'), width: 240, height: 240, alt: "три ромашки и цифра 3" },
  'p001_cover_fish_4': { source: require('../../assets/book2/p001_cover_fish_4.png'), width: 310, height: 310, alt: "четыре рыбки и цифра 4" },
  'p001_cover_chicks_5': { source: require('../../assets/book2/p001_cover_chicks_5.png'), width: 310, height: 310, alt: "пять цыплят и цифра 5" },
  'p001_cover_red_currants_6': { source: require('../../assets/book2/p001_cover_red_currants_6.png'), width: 310, height: 253, alt: "шесть ягод красной смородины и цифра 6" },
  'p001_cover_black_currants_7': { source: require('../../assets/book2/p001_cover_black_currants_7.png'), width: 310, height: 249, alt: "семь ягод чёрной смородины и цифра 7" },
  'p003_school_children': { source: require('../../assets/book2/p003_school_children.png'), width: 680, height: 578, alt: "8 детей идут к современной школе: две девочки, два мальчика и две смешанные пары" },
  'p003_balls_bigger_smaller': { source: require('../../assets/book2/p003_balls_bigger_smaller.png'), width: 887, height: 439, alt: "большой бирюзовый мяч слева и маленький красный мяч справа" },
  'p003_pencils_longer_shorter': { source: require('../../assets/book2/p003_pencils_longer_shorter.png'), width: 1010, height: 382, alt: "длинный зелёный карандаш сверху и короткий красный снизу" },
  'p004_boys_river_bathing': { source: require('../../assets/book2/p004_boys_river_bathing.png'), width: 724, height: 543, alt: "10 детей у реки: один у дерева, двое с лодочкой, трое на переднем плане и четверо в воде справа; 5 деревьев, 1 собака и 1 лодочка" },
  'p005_field_harvest_sacks': { source: require('../../assets/book2/p005_field_harvest_sacks.png'), width: 795, height: 550, alt: "современный огород: дети и взрослые собирают овощи; вдоль дорожки стоят ровно шесть отдельных ящиков с урожаем" },
  'p005_bowl_cucumbers': { source: require('../../assets/book2/p005_bowl_cucumbers.png'), width: 345, height: 200, alt: "семь отдельных огурцов перед пустой миской: три сзади и четыре спереди" },
  'p005_basket_tomatoes': { source: require('../../assets/book2/p005_basket_tomatoes.png'), width: 340, height: 200, alt: "восемь отдельных помидоров перед пустым ящиком: четыре сзади и четыре спереди" },
};
