"""Create app-only JPEG copies and Metro's static asset registry. Sources stay untouched."""
import json
from pathlib import Path
from PIL import Image
root=Path(__file__).resolve().parents[1]
assets=[a for a in json.loads((root/'textbook/data/assets.json').read_text()) if a['page']<=10]
entries=[]
for a in assets:
    out=root/'assets/book'/f"{a['id']}.jpg"
    im=Image.open(root/'textbook'/a['path']).convert('RGB')
    im.thumbnail((1100,1100)); im.save(out,quality=92,optimize=True)
    entries.append(f"  '{a['id']}': {{ source: require('../../assets/book/{out.name}'), width: {im.width}, height: {im.height}, alt: {json.dumps(a['description'],ensure_ascii=False)} }},")
for p in range(1,11):
    im=Image.open(root/f'textbook/pages/page_{p:03}.png').convert('RGB')
    im.thumbnail((1200,1800)); out=root/f'assets/book/page_{p:03}.jpg';im.save(out,quality=92,optimize=True)
    entries.append(f"  'page_{p:03}': {{ source: require('../../assets/book/{out.name}'), width: {im.width}, height: {im.height}, alt: 'Оригинал страницы {p}' }},")
(root/'src/content/assets.ts').write_text("// Generated by scripts/prepare_assets.py\nimport type { ImageSourcePropType } from 'react-native';\nexport const assets: Record<string, { source: ImageSourcePropType; width: number; height: number; alt: string }> = {\n"+'\n'.join(entries)+'\n};\n')
print(f'{len(assets)} illustrations + 10 scans prepared')
