"""Create compact WebP copies of the revised raster art for the web build.

The PNG originals remain the sources for iOS and Android. Metro chooses the
matching @2x WebP automatically for high-density browser displays.
"""

import argparse
import hashlib
import json
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "assets/book2"
REGISTRY = ROOT / "src/content/revisedAssets.web.ts"
NATIVE_REGISTRY = ROOT / "src/content/revisedAssets.ts"
SOURCE_HASHES = ART / "webp-source-hashes.json"
IDS = [item["id"] for item in json.loads((ART / "manifest.json").read_text())]
ENCODING = "cwebp -q 90 -m 6 -sharp_yuv -alpha_q 100"


def source_and_output(asset_id, retina):
    suffix = "@2x" if retina else ""
    return ART / f"{asset_id}{suffix}.png", ART / f"{asset_id}{suffix}.webp"


def encode(pair):
    source, output = pair
    subprocess.run(
        [
            "cwebp",
            "-quiet",
            "-q",
            "90",
            "-m",
            "6",
            "-sharp_yuv",
            "-alpha_q",
            "100",
            str(source),
            "-o",
            str(output),
        ],
        check=True,
    )


def registry_text():
    native = NATIVE_REGISTRY.read_text()
    web, count = re.subn(
        r"(\.\./\.\./assets/book2/[a-zA-Z0-9_]+)\.png",
        r"\1.webp",
        native,
    )
    if count != len(IDS):
        raise ValueError(f"Expected {len(IDS)} raster references, found {count}")
    return web.replace(
        "// Generated by scripts/prepare_assets.py --set revised",
        "// Generated by scripts/prepare_web_assets.py",
        1,
    )


def verify(pair):
    source, output = pair
    if not output.is_file():
        raise FileNotFoundError(output)
    with Image.open(source) as original, Image.open(output) as compressed:
        if compressed.format != "WEBP" or compressed.size != original.size:
            raise ValueError(f"WebP format or dimensions changed: {output}")
        alpha = original.getchannel("A") if "A" in original.getbands() else None
        if alpha and alpha.getextrema()[0] < 255 and "A" not in compressed.getbands():
            raise ValueError(f"Transparency was lost: {output}")
    if output.stat().st_size >= source.stat().st_size:
        raise ValueError(f"WebP is not smaller than PNG: {output}")


def source_hashes(pairs):
    hashes = {
        source.name: hashlib.sha256(source.read_bytes()).hexdigest()
        for source, _ in pairs
    }
    return json.dumps({"encoding": ENCODING, "sources": hashes}, indent=2, sort_keys=True) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    pairs = [source_and_output(asset_id, retina) for asset_id in IDS for retina in (False, True)]
    if not args.check:
        with ThreadPoolExecutor(max_workers=4) as pool:
            list(pool.map(encode, pairs))
        REGISTRY.write_text(registry_text())
        SOURCE_HASHES.write_text(source_hashes(pairs))
    for pair in pairs:
        verify(pair)
    if REGISTRY.read_text() != registry_text():
        raise ValueError(f"Outdated WebP asset registry: {REGISTRY}")
    if SOURCE_HASHES.read_text() != source_hashes(pairs):
        raise ValueError("A revised PNG changed without regenerating its WebP copy")
    original_bytes = sum(source.stat().st_size for source, _ in pairs)
    web_bytes = sum(output.stat().st_size for _, output in pairs)
    print(f"{len(IDS)} illustrations, 1x and 2x: {original_bytes // 1024} KiB PNG -> {web_bytes // 1024} KiB WebP")


if __name__ == "__main__":
    main()
