/** Language names stay in their own language so visitors can always find them. */
export const libraryLanguages = [
  { code: "ru", name: "Русский" },
  { code: "en", name: "English" },
  { code: "de", name: "Deutsch" },
  { code: "fr", name: "Français" },
  { code: "es", name: "Español" },
  { code: "it", name: "Italiano" },
] as const;
export type LibraryLocale = (typeof libraryLanguages)[number]["code"];
export function libraryLocale(value: string | null): LibraryLocale {
  return libraryLanguages.some((language) => language.code === value)
    ? (value as LibraryLocale)
    : "ru";
}
export const LANGUAGE_STORAGE_KEY = "uchebnik:library-language:v1";

const ru = {
  title: "Умная Полка",
  chooseBook: "Выбери учебник",
  subtitle: "По проверенным методикам 1950-х годов",
  language: "Язык",
  searchLanguages: "Найти язык",
  closeLanguages: "Закрыть выбор языка",
  noLanguages: "Язык не найден",
  languageSaveError: "Не удалось запомнить язык на этом устройстве.",
  parents: "Родителям",
  parentsLabel: "Информация для родителей",
  parentsTitle: "Учимся вместе",
  parentsBody:
    "Выберите учебник на полке. Ответы и рисунки сохраняются на этом устройстве. Настройки прогресса находятся внутри каждого учебника, в разделе «Родителям».",
  back: "Вернуться в библиотеку",
  supportTitle: "Новые учебники и озвучка",
  support: "Поддержать проект",
  supportLabel: "Поддержать проект на Boosty",
  supportSoon: "Boosty — скоро",
  supportError: "Не удалось открыть Boosty. Попробуйте ещё раз.",
  fundingLabel: "Сбор на новые учебники и озвучку",
  funding: "{raised} из {goal}",
  fundingAccessible: "Собрано {raised} из {goal}",
  arithmetic: "Арифметика",
  grade: "1 класс",
  methodology: "По методике А. С. Пчёлко и Г. Б. Поляка",
  bookLanguage: "Учебник на русском",
  openBook: "Открыть учебник Арифметика, 1 класс",
  cover: "Обложка учебника Арифметика, 1 класс",
  progress: "Пройдено {completed} из {total} страниц",
  start: "Начать учиться",
  resume: "Продолжить",
  startLabel: "Начать заниматься  →",
  resumeLabel: "Продолжить занятие  →",
  contents: "Оглавление",
  contentsLabel: "Оглавление учебника Арифметика",
  moreSubjects: "Дальше — больше предметов",
  planned: "В планах",
  books: {
    russian: "Русский язык",
    reading: "Чтение",
    nature: "Мир природы",
    physics: "Физика",
    geography: "География",
    history: "История",
    biology: "Биология",
    chemistry: "Химия",
    algebra: "Алгебра",
  },
};
export type LibraryCopy = {
  [Key in Exclude<keyof typeof ru, "books">]: string;
} & { books: Record<keyof typeof ru.books, string> };
export const libraryCopy: Record<LibraryLocale, LibraryCopy> = {
  ru,
  en: {
    title: "Smart Shelf",
    chooseBook: "Choose a textbook",
    subtitle: "Based on proven teaching methods from the 1950s",
    language: "Language",
    searchLanguages: "Find a language",
    closeLanguages: "Close language selection",
    noLanguages: "No languages found",
    languageSaveError: "Could not save your language on this device.",
    parents: "For parents",
    parentsLabel: "Information for parents",
    parentsTitle: "Learning together",
    parentsBody:
      "Choose a textbook from the shelf. Answers and drawings are saved on this device. Progress settings are inside each textbook, under “Родителям” (For parents).",
    back: "Back to the library",
    supportTitle: "More textbooks and audio",
    support: "Support the project",
    supportLabel: "Support the project on Boosty",
    supportSoon: "Boosty — coming soon",
    supportError: "Could not open Boosty. Please try again.",
    fundingLabel: "Fundraising for new textbooks and audio",
    funding: "{raised} of {goal}",
    fundingAccessible: "{raised} raised towards {goal}",
    arithmetic: "Arithmetic",
    grade: "Grade 1",
    methodology: "Based on the methods of A. S. Pchelko and G. B. Polyak",
    bookLanguage: "Textbook in Russian",
    openBook: "Open Arithmetic, Grade 1",
    cover: "Arithmetic, Grade 1 textbook cover",
    progress: "{completed} of {total} pages completed",
    start: "Start learning",
    resume: "Continue",
    startLabel: "Start learning →",
    resumeLabel: "Continue learning →",
    contents: "Contents",
    contentsLabel: "Arithmetic contents",
    moreSubjects: "More subjects to come",
    planned: "Planned",
    books: {
      russian: "Russian",
      reading: "Reading",
      nature: "Nature",
      physics: "Physics",
      geography: "Geography",
      history: "History",
      biology: "Biology",
      chemistry: "Chemistry",
      algebra: "Algebra",
    },
  },
  de: {
    title: "Smart Shelf",
    chooseBook: "Wähle dein Schulbuch",
    subtitle: "Nach bewährten Lehrmethoden der 1950er-Jahre",
    language: "Sprache",
    searchLanguages: "Sprache suchen",
    closeLanguages: "Sprachauswahl schließen",
    noLanguages: "Keine Sprache gefunden",
    languageSaveError:
      "Die Sprache konnte auf diesem Gerät nicht gespeichert werden.",
    parents: "Für Eltern",
    parentsLabel: "Informationen für Eltern",
    parentsTitle: "Gemeinsam lernen",
    parentsBody:
      "Wählen Sie ein Schulbuch aus dem Regal. Antworten und Zeichnungen werden auf diesem Gerät gespeichert. Die Einstellungen zum Lernfortschritt finden Sie im jeweiligen Schulbuch unter „Родителям“ (Für Eltern).",
    back: "Zurück zur Bibliothek",
    supportTitle: "Neue Schulbücher und Vertonung",
    support: "Projekt unterstützen",
    supportLabel: "Projekt auf Boosty unterstützen",
    supportSoon: "Boosty — bald verfügbar",
    supportError:
      "Boosty konnte nicht geöffnet werden. Bitte erneut versuchen.",
    fundingLabel: "Spenden für neue Schulbücher und Vertonung",
    funding: "{raised} von {goal}",
    fundingAccessible: "{raised} von {goal} gesammelt",
    arithmetic: "Arithmetik",
    grade: "1. Klasse",
    methodology: "Nach den Methoden von A. S. Pchelko und G. B. Polyak",
    bookLanguage: "Schulbuch auf Russisch",
    openBook: "Arithmetik, 1. Klasse öffnen",
    cover: "Buchcover Arithmetik, 1. Klasse",
    progress: "{completed} von {total} Seiten abgeschlossen",
    start: "Lernen starten",
    resume: "Weiterlernen",
    startLabel: "Lernen starten →",
    resumeLabel: "Weiterlernen →",
    contents: "Inhalt",
    contentsLabel: "Inhaltsverzeichnis Arithmetik",
    moreSubjects: "Weitere Fächer folgen",
    planned: "Geplant",
    books: {
      russian: "Russisch",
      reading: "Lesen",
      nature: "Naturkunde",
      physics: "Physik",
      geography: "Geografie",
      history: "Geschichte",
      biology: "Biologie",
      chemistry: "Chemie",
      algebra: "Algebra",
    },
  },
  fr: {
    title: "Smart Shelf",
    chooseBook: "Choisissez un manuel",
    subtitle: "Des méthodes pédagogiques éprouvées des années 1950",
    language: "Langue",
    searchLanguages: "Rechercher une langue",
    closeLanguages: "Fermer le choix de langue",
    noLanguages: "Aucune langue trouvée",
    languageSaveError: "Impossible de mémoriser la langue sur cet appareil.",
    parents: "Pour les parents",
    parentsLabel: "Informations pour les parents",
    parentsTitle: "Apprendre ensemble",
    parentsBody:
      "Choisissez un manuel sur l’étagère. Les réponses et les dessins sont enregistrés sur cet appareil. Les réglages de progression se trouvent dans chaque manuel, sous « Родителям » (Pour les parents).",
    back: "Retour à la bibliothèque",
    supportTitle: "De nouveaux manuels et de l’audio",
    support: "Soutenir le projet",
    supportLabel: "Soutenir le projet sur Boosty",
    supportSoon: "Boosty — bientôt disponible",
    supportError: "Impossible d’ouvrir Boosty. Veuillez réessayer.",
    fundingLabel: "Collecte pour de nouveaux manuels et de l’audio",
    funding: "{raised} sur {goal}",
    fundingAccessible: "{raised} collectés sur un objectif de {goal}",
    arithmetic: "Arithmétique",
    grade: "1re année",
    methodology: "Selon les méthodes d’A. S. Pchelko et de G. B. Polyak",
    bookLanguage: "Manuel en russe",
    openBook: "Ouvrir Arithmétique, 1re année",
    cover: "Couverture du manuel Arithmétique, 1re année",
    progress: "{completed} pages terminées sur {total}",
    start: "Commencer",
    resume: "Continuer",
    startLabel: "Commencer à apprendre →",
    resumeLabel: "Continuer à apprendre →",
    contents: "Sommaire",
    contentsLabel: "Sommaire du manuel d’arithmétique",
    moreSubjects: "D’autres matières à venir",
    planned: "À venir",
    books: {
      russian: "Russe",
      reading: "Lecture",
      nature: "Nature",
      physics: "Physique",
      geography: "Géographie",
      history: "Histoire",
      biology: "Biologie",
      chemistry: "Chimie",
      algebra: "Algèbre",
    },
  },
  es: {
    title: "Smart Shelf",
    chooseBook: "Elige un libro",
    subtitle: "Basados en métodos de enseñanza probados de los años 50",
    language: "Idioma",
    searchLanguages: "Buscar un idioma",
    closeLanguages: "Cerrar selección de idioma",
    noLanguages: "No se encontraron idiomas",
    languageSaveError: "No se pudo guardar el idioma en este dispositivo.",
    parents: "Para familias",
    parentsLabel: "Información para las familias",
    parentsTitle: "Aprendemos juntos",
    parentsBody:
      "Elige un libro de la estantería. Las respuestas y los dibujos se guardan en este dispositivo. Los ajustes de progreso están dentro de cada libro, en «Родителям» (Para familias).",
    back: "Volver a la biblioteca",
    supportTitle: "Más libros de texto y audio",
    support: "Apoyar el proyecto",
    supportLabel: "Apoyar el proyecto en Boosty",
    supportSoon: "Boosty — próximamente",
    supportError: "No se pudo abrir Boosty. Inténtalo de nuevo.",
    fundingLabel: "Recaudación para nuevos libros de texto y audio",
    funding: "{raised} de {goal}",
    fundingAccessible: "{raised} recaudados de un objetivo de {goal}",
    arithmetic: "Aritmética",
    grade: "1.er curso",
    methodology: "Según los métodos de A. S. Pchelko y G. B. Polyak",
    bookLanguage: "Libro en ruso",
    openBook: "Abrir Aritmética, 1.er curso",
    cover: "Portada del libro Aritmética, 1.er curso",
    progress: "{completed} de {total} páginas completadas",
    start: "Empezar a aprender",
    resume: "Continuar",
    startLabel: "Empezar a aprender →",
    resumeLabel: "Continuar aprendiendo →",
    contents: "Índice",
    contentsLabel: "Índice de Aritmética",
    moreSubjects: "Próximamente, más asignaturas",
    planned: "En preparación",
    books: {
      russian: "Ruso",
      reading: "Lectura",
      nature: "Naturaleza",
      physics: "Física",
      geography: "Geografía",
      history: "Historia",
      biology: "Biología",
      chemistry: "Química",
      algebra: "Álgebra",
    },
  },
  it: {
    title: "Smart Shelf",
    chooseBook: "Scegli un libro",
    subtitle: "Basati su metodi didattici collaudati degli anni ’50",
    language: "Lingua",
    searchLanguages: "Cerca una lingua",
    closeLanguages: "Chiudi la selezione della lingua",
    noLanguages: "Nessuna lingua trovata",
    languageSaveError: "Impossibile salvare la lingua su questo dispositivo.",
    parents: "Per i genitori",
    parentsLabel: "Informazioni per i genitori",
    parentsTitle: "Impariamo insieme",
    parentsBody:
      "Scegli un libro dallo scaffale. Le risposte e i disegni vengono salvati su questo dispositivo. Le impostazioni dei progressi si trovano in ogni libro, nella sezione «Родителям» (Per i genitori).",
    back: "Torna alla biblioteca",
    supportTitle: "Nuovi libri di testo e audio",
    support: "Sostieni il progetto",
    supportLabel: "Sostieni il progetto su Boosty",
    supportSoon: "Boosty — prossimamente",
    supportError: "Impossibile aprire Boosty. Riprova.",
    fundingLabel: "Raccolta fondi per nuovi libri di testo e audio",
    funding: "{raised} su {goal}",
    fundingAccessible: "{raised} raccolti su un obiettivo di {goal}",
    arithmetic: "Aritmetica",
    grade: "1ª classe",
    methodology: "Secondo i metodi di A. S. Pchelko e G. B. Polyak",
    bookLanguage: "Libro in russo",
    openBook: "Apri Aritmetica, 1ª classe",
    cover: "Copertina del libro Aritmetica, 1ª classe",
    progress: "{completed} pagine completate su {total}",
    start: "Inizia a imparare",
    resume: "Continua",
    startLabel: "Inizia a imparare →",
    resumeLabel: "Continua a imparare →",
    contents: "Indice",
    contentsLabel: "Indice di Aritmetica",
    moreSubjects: "Altre materie in arrivo",
    planned: "In programma",
    books: {
      russian: "Russo",
      reading: "Lettura",
      nature: "Natura",
      physics: "Fisica",
      geography: "Geografia",
      history: "Storia",
      biology: "Biologia",
      chemistry: "Chimica",
      algebra: "Algebra",
    },
  },
};
export function libraryText(
  template: string,
  values: Record<string, string | number>,
) {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    String(values[key] ?? match),
  );
}
