"""Record narrator phrases with a TTS provider and write the manifest the app plays from.

    npm run tts:phrases                      # list phrases (docs/narration-phrases.json)
    python3 scripts/tts/generate.py          # dry run: what would be recorded
    YANDEX_API_KEY=… YANDEX_FOLDER_ID=… python3 scripts/tts/generate.py --provider yandex --voice marina
    ELEVENLABS_API_KEY=… python3 scripts/tts/generate.py --provider elevenlabs --voice <voice_id>

Recordings go to public/audio/<key>.mp3 (copied into the web export); src/content/audioManifest.ts
maps each phrase key to its file. Only phrases without a recording are requested, so a changed text
re-records just itself. Keys never enter the client build.
"""
import argparse, json, os, pathlib, sys, urllib.request
ROOT = pathlib.Path(__file__).resolve().parents[2]
AUDIO = ROOT / "public/audio"
MANIFEST = ROOT / "src/content/audioManifest.ts"

def phrase_key(text: str) -> str:
    h = 5381
    for ch in text.strip():
        h = ((h << 5) + h + ord(ch)) & 0xFFFFFFFF
    return f"{h:08x}"

def yandex(text, voice, key, folder):
    data = urllib.parse.urlencode({"text": text, "lang": "ru-RU", "voice": voice, "format": "mp3", "folderId": folder}).encode()
    req = urllib.request.Request("https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize", data=data, headers={"Authorization": f"Api-Key {key}"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()

def elevenlabs(text, voice, key):
    body = json.dumps({"text": text, "model_id": "eleven_multilingual_v2"}).encode()
    req = urllib.request.Request(f"https://api.elevenlabs.io/v1/text-to-speech/{voice}", data=body, headers={"xi-api-key": key, "Content-Type": "application/json", "Accept": "audio/mpeg"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()

def main():
    import urllib.parse  # noqa: F401  (used by yandex)
    ap = argparse.ArgumentParser()
    ap.add_argument("--provider", choices=["yandex", "elevenlabs"], default=None)
    ap.add_argument("--voice", default="marina")
    ap.add_argument("--limit", type=int, default=0, help="record at most N phrases (for a listening test)")
    args = ap.parse_args()
    phrases = json.loads((ROOT / "docs/narration-phrases.json").read_text(encoding="utf-8"))
    for p in phrases:
        assert phrase_key(p["text"]) == p["key"], "phrase key mismatch between JS and Python"
    AUDIO.mkdir(parents=True, exist_ok=True)
    have = {f.stem for f in AUDIO.glob("*.mp3")}
    todo = [p for p in phrases if p["key"] not in have]
    print(f"{len(phrases)} phrases, {len(have)} recorded, {len(todo)} to record")
    if args.provider:
        key = os.environ.get("YANDEX_API_KEY" if args.provider == "yandex" else "ELEVENLABS_API_KEY")
        if not key:
            sys.exit("provider key missing in the environment")
        for i, p in enumerate(todo[: args.limit or None]):
            audio = yandex(p["spoken"], args.voice, key, os.environ["YANDEX_FOLDER_ID"]) if args.provider == "yandex" else elevenlabs(p["spoken"], args.voice, key)
            (AUDIO / f"{p['key']}.mp3").write_bytes(audio)
            print(f"{i + 1}/{len(todo)} {p['key']} {p['spoken'][:60]}")
    else:
        for p in todo[:10]:
            print(f"  would record {p['key']}: {p['spoken'][:80]}")
    have = {f.stem for f in AUDIO.glob("*.mp3")}
    manifest = {p["key"]: f"{p['key']}.mp3" for p in phrases if p["key"] in have}
    MANIFEST.write_text("// Generated by scripts/tts/generate.py: phrase key → recording under public/audio/. Empty until recordings exist.\n"
                        "export const audioManifest: Record<string, string> = " + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
    print(f"manifest: {len(manifest)} recordings")

if __name__ == "__main__":
    main()
